In [107]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [108]:
# Assuming the dataset is in the same directory as your notebook
df = pd.read_csv('dataset.csv')

In [109]:
df

Marital status  Application mode  Application order  Course  \
0                  1                 8                  5       2   
1                  1                 6                  1      11   
2                  1                 1                  5       5   
3                  1                 8                  2      15   
4                  2                12                  1       3   
...              ...               ...                ...     ...   
4419               1                 1                  6      15   
4420               1                 1                  2      15   
4421               1                 1                  1      12   
4422               1                 1                  1       9   
4423               1                 5                  1      15   

      Daytime/evening attendance  Previous qualification  Nacionality  \
0                              1                       1            1   
1                              1                       1            1   
2                              1                       1            1   
3                              1                       1            1   
4                              0                       1            1   
...                          ...                     ...          ...   
4419                           1                       1            1   
4420                           1                       1           19   
4421                           1                       1            1   
4422                           1                       1            1   
4423                           1                       1            9   

      Mother's qualification  Father's qualification  Mother's occupation  \
0                         13                      10                    6   
1                          1                       3                    4   
2                         22                      27                   10   
3                         23                      27                    6   
4                         22                      28                   10   
...                      ...                     ...                  ...   
4419                       1                       1                    6   
4420                       1                       1                   10   
4421                      22                      27                   10   
4422                      22                      27                    8   
4423                      23                      27                    6   

      ...  Curricular units 2nd sem (credited)  \
0     ...                                    0   
1     ...                                    0   
2     ...                                    0   
3     ...                                    0   
4     ...                                    0   
...   ...                                  ...   
4419  ...                                    0   
4420  ...                                    0   
4421  ...                                    0   
4422  ...                                    0   
4423  ...                                    0   

      Curricular units 2nd sem (enrolled)  \
0                                       0   
1                                       6   
2                                       6   
3                                       6   
4                                       6   
...                                   ...   
4419                                    6   
4420                                    6   
4421                                    8   
4422                                    5   
4423                                    6   

      Curricular units 2nd sem (evaluations)  \
0                                          0   
1                                          6   
2                                          0   
3                                        

In [110]:
# Count occurrences for all unique values in the column
print(df['Target'].value_counts())

Target
Graduate    2209
Dropout     1421
Enrolled     794
Name: count, dtype: int64


In [111]:
# Get 1400 of graduate and droput:
graduate_df = df[df['Target'] == 'Graduate'].head(1400)
dropout_df = df[df['Target'] == 'Dropout'].head(1400)

# Combine the dataframes
combined_df = pd.concat([graduate_df, dropout_df])

# Reset the index to ensure that the rows are properly randomized
combined_df = combined_df.reset_index(drop=True)

# Shuffle (randomize) the rows
combined_df = combined_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Now, combined_df contains the combined and randomized data

In [112]:
combined_df

Marital status  Application mode  Application order  Course  \
0                  1                 8                  5      13   
1                  1                 9                  2      12   
2                  2                12                  1      17   
3                  1                 8                  4      12   
4                  1                12                  1      14   
...              ...               ...                ...     ...   
2795               1                 1                  1      15   
2796               1                 1                  1      14   
2797               1                 1                  1       5   
2798               1                 1                  2      11   
2799               1                 1                  1       6   

      Daytime/evening attendance  Previous qualification  Nacionality  \
0                              1                       1            1   
1                              1                       1            1   
2                              0                       1            1   
3                              1                       1            1   
4                              1                       1            1   
...                          ...                     ...          ...   
2795                           1                       1            1   
2796                           1                       1            1   
2797                           1                       1            1   
2798                           1                       1            1   
2799                           1                       1            1   

      Mother's qualification  Father's qualification  Mother's occupation  \
0                         13                      14                   10   
1                         23                      27                    6   
2                         22                      14                   10   
3                         23                      27                    6   
4                         22                      27                   12   
...                      ...                     ...                  ...   
2795                      19                      28                    1   
2796                       1                      27                    2   
2797                      13                       1                    6   
2798                       4                       3                    8   
2799                      22                      28                    7   

      ...  Curricular units 2nd sem (credited)  \
0     ...                                    0   
1     ...                                    0   
2     ...                                    0   
3     ...                                    0   
4     ...                                    0   
...   ...                                  ...   
2795  ...                                    0   
2796  ...                                    0   
2797  ...                                    0   
2798  ...                                    0   
2799  ...                                    0   

      Curricular units 2nd sem (enrolled)  \
0                                       8   
1                                       8   
2                                       5   
3                                       8   
4                                       6   
...                                   ...   
2795                                    6   
2796                                    6   
2797                                    6   
2798                                    6   
2799                                    5   

      Curricular units 2nd sem (evaluations)  \
0                                          8   
1                                          8   
2                                          8   
3                                        

In [113]:
print(combined_df['Target'].value_counts())

Target
Graduate    1400
Dropout     1400
Name: count, dtype: int64


In [114]:
# Display the null counts for each column
print(combined_df.isnull().sum())

Marital status                                    0
Application mode                                  0
Application order                                 0
Course                                            0
Daytime/evening attendance                        0
Previous qualification                            0
Nacionality                                       0
Mother's qualification                            0
Father's qualification                            0
Mother's occupation                               0
Father's occupation                               0
Displaced                                         0
Educational special needs                         0
Debtor                                            0
Tuition fees up to date                           0
Gender                                            0
Scholarship holder                                0
Age at enrollment                                 0
International                                     0
Curricular u

In [115]:
# Print all columns
print(combined_df.columns)

Index(['Marital status', 'Application mode', 'Application order', 'Course',
       'Daytime/evening attendance', 'Previous qualification', 'Nacionality',
       'Mother's qualification', 'Father's qualification',
       'Mother's occupation', 'Father's occupation', 'Displaced',
       'Educational special needs', 'Debtor', 'Tuition fees up to date',
       'Gender', 'Scholarship holder', 'Age at enrollment', 'International',
       'Curricular units 1st sem (credited)',
       'Curricular units 1st sem (enrolled)',
       'Curricular units 1st sem (evaluations)',
       'Curricular units 1st sem (approved)',
       'Curricular units 1st sem (grade)',
       'Curricular units 1st sem (without evaluations)',
       'Curricular units 2nd sem (credited)',
       'Curricular units 2nd sem (enrolled)',
       'Curricular units 2nd sem (evaluations)',
       'Curricular units 2nd sem (approved)',
       'Curricular units 2nd sem (grade)',
       'Curricular units 2nd sem (without evaluations)

In [116]:
X = df.drop(columns=['Target', 'Curricular units 1st sem (enrolled)', 'Curricular units 2nd sem (enrolled)']).to_numpy()
y = df['Target']

In [117]:
X_reshaped = X.reshape(-1, 8, 4)
print(X_reshaped.shape)

(4424, 8, 4)


In [118]:
print(y)

0        Dropout
1       Graduate
2        Dropout
3       Graduate
4       Graduate
          ...   
4419    Graduate
4420     Dropout
4421     Dropout
4422    Graduate
4423    Graduate
Name: Target, Length: 4424, dtype: object


In [119]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
y_final = to_categorical(y_encoded, num_classes=3)
print(y_final)

[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [124]:
from sklearn.model_selection import train_test_split

# Splitting a dataset into a training set and a testing set
X_train, X_test, y_train, y_test = train_test_split(X_reshaped, y_final, test_size=0.2, random_state=42)

In [125]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [126]:
model = keras.Sequential([
    layers.Flatten(input_shape=(8, 4)),  # Flatten the 8x4 input into a 32-element vector
    layers.Dense(128, activation='relu'),  # 64 neurons in the hidden layer with ReLU activation
    layers.Dense(128, activation='relu'),  # 64 neurons in the hidden layer with ReLU activation
    layers.Dense(128, activation='relu'),  # 64 neurons in the hidden layer with ReLU activation
    layers.Dense(3, activation='softmax')  # Output layer with softmax activation for classification
])

In [127]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [128]:
history = model.fit(X_train, y_train, epochs=100)

Epoch 1/100
111/111 [==============================] - 1s 1ms/step - loss: 0.7762 - accuracy: 0.6807
Epoch 2/100
111/111 [==============================] - 0s 1ms/step - loss: 0.6508 - accuracy: 0.7279
Epoch 3/100
111/111 [==============================] - 0s 1ms/step - loss: 0.6208 - accuracy: 0.7431
Epoch 4/100
111/111 [==============================] - 0s 1ms/step - loss: 0.6067 - accuracy: 0.7502
Epoch 5/100
111/111 [==============================] - 0s 1ms/step - loss: 0.6089 - accuracy: 0.7443
Epoch 6/100
111/111 [==============================] - 0s 1ms/step - loss: 0.5915 - accuracy: 0.7550
Epoch 7/100
111/111 [==============================] - 0s 1ms/step - loss: 0.5680 - accuracy: 0.7672
Epoch 8/100
111/111 [==============================] - 0s 1ms/step - loss: 0.5420 - accuracy: 0.7779
Epoch 9/100
111/111 [==============================] - 0s 1ms/step - loss: 0.5332 - accuracy: 0.7804
Epoch 10/100
111/111 [==============================] - 0s 1ms/step - loss: 0.5258 - accura

In [129]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {test_accuracy * 100:.2f}%")

28/28 [==============================] - 0s 889us/step - loss: 2.7573 - accuracy: 0.7153
Test Accuracy: 71.53%
