In [96]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [97]:
# Assuming the dataset is in the same directory as your notebook
df = pd.read_csv('dataset.csv')

In [98]:
df

Marital status  Application mode  Application order  Course  \
0                  1                 8                  5       2   
1                  1                 6                  1      11   
2                  1                 1                  5       5   
3                  1                 8                  2      15   
4                  2                12                  1       3   
...              ...               ...                ...     ...   
4419               1                 1                  6      15   
4420               1                 1                  2      15   
4421               1                 1                  1      12   
4422               1                 1                  1       9   
4423               1                 5                  1      15   

      Daytime/evening attendance  Previous qualification  Nacionality  \
0                              1                       1            1   
1                              1                       1            1   
2                              1                       1            1   
3                              1                       1            1   
4                              0                       1            1   
...                          ...                     ...          ...   
4419                           1                       1            1   
4420                           1                       1           19   
4421                           1                       1            1   
4422                           1                       1            1   
4423                           1                       1            9   

      Mother's qualification  Father's qualification  Mother's occupation  \
0                         13                      10                    6   
1                          1                       3                    4   
2                         22                      27                   10   
3                         23                      27                    6   
4                         22                      28                   10   
...                      ...                     ...                  ...   
4419                       1                       1                    6   
4420                       1                       1                   10   
4421                      22                      27                   10   
4422                      22                      27                    8   
4423                      23                      27                    6   

      ...  Curricular units 2nd sem (credited)  \
0     ...                                    0   
1     ...                                    0   
2     ...                                    0   
3     ...                                    0   
4     ...                                    0   
...   ...                                  ...   
4419  ...                                    0   
4420  ...                                    0   
4421  ...                                    0   
4422  ...                                    0   
4423  ...                                    0   

      Curricular units 2nd sem (enrolled)  \
0                                       0   
1                                       6   
2                                       6   
3                                       6   
4                                       6   
...                                   ...   
4419                                    6   
4420                                    6   
4421                                    8   
4422                                    5   
4423                                    6   

      Curricular units 2nd sem (evaluations)  \
0                                          0   
1                                          6   
2                                          0   
3                                        

In [99]:
# Count occurrences for all unique values in the column
print(df['Target'].value_counts())

Target
Graduate    2209
Dropout     1421
Enrolled     794
Name: count, dtype: int64


In [100]:
# Get 1400 of graduate and droput:
graduate_df = df[df['Target'] == 'Graduate'].head(1400)
dropout_df = df[df['Target'] == 'Dropout'].head(1400)

# Combine the dataframes
combined_df = pd.concat([graduate_df, dropout_df])

# Reset the index to ensure that the rows are properly randomized
combined_df = combined_df.reset_index(drop=True)

# Shuffle (randomize) the rows
combined_df = combined_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Now, combined_df contains the combined and randomized data

In [101]:
combined_df

Marital status  Application mode  Application order  Course  \
0                  1                 8                  5      13   
1                  1                 9                  2      12   
2                  2                12                  1      17   
3                  1                 8                  4      12   
4                  1                12                  1      14   
...              ...               ...                ...     ...   
2795               1                 1                  1      15   
2796               1                 1                  1      14   
2797               1                 1                  1       5   
2798               1                 1                  2      11   
2799               1                 1                  1       6   

      Daytime/evening attendance  Previous qualification  Nacionality  \
0                              1                       1            1   
1                              1                       1            1   
2                              0                       1            1   
3                              1                       1            1   
4                              1                       1            1   
...                          ...                     ...          ...   
2795                           1                       1            1   
2796                           1                       1            1   
2797                           1                       1            1   
2798                           1                       1            1   
2799                           1                       1            1   

      Mother's qualification  Father's qualification  Mother's occupation  \
0                         13                      14                   10   
1                         23                      27                    6   
2                         22                      14                   10   
3                         23                      27                    6   
4                         22                      27                   12   
...                      ...                     ...                  ...   
2795                      19                      28                    1   
2796                       1                      27                    2   
2797                      13                       1                    6   
2798                       4                       3                    8   
2799                      22                      28                    7   

      ...  Curricular units 2nd sem (credited)  \
0     ...                                    0   
1     ...                                    0   
2     ...                                    0   
3     ...                                    0   
4     ...                                    0   
...   ...                                  ...   
2795  ...                                    0   
2796  ...                                    0   
2797  ...                                    0   
2798  ...                                    0   
2799  ...                                    0   

      Curricular units 2nd sem (enrolled)  \
0                                       8   
1                                       8   
2                                       5   
3                                       8   
4                                       6   
...                                   ...   
2795                                    6   
2796                                    6   
2797                                    6   
2798                                    6   
2799                                    5   

      Curricular units 2nd sem (evaluations)  \
0                                          8   
1                                          8   
2                                          8   
3                                        

In [102]:
print(combined_df['Target'].value_counts())

Target
Graduate    1400
Dropout     1400
Name: count, dtype: int64


In [103]:
# Display the null counts for each column
print(combined_df.isnull().sum())

Marital status                                    0
Application mode                                  0
Application order                                 0
Course                                            0
Daytime/evening attendance                        0
Previous qualification                            0
Nacionality                                       0
Mother's qualification                            0
Father's qualification                            0
Mother's occupation                               0
Father's occupation                               0
Displaced                                         0
Educational special needs                         0
Debtor                                            0
Tuition fees up to date                           0
Gender                                            0
Scholarship holder                                0
Age at enrollment                                 0
International                                     0
Curricular u

In [104]:
# Print all columns
print(combined_df.columns)

Index(['Marital status', 'Application mode', 'Application order', 'Course',
       'Daytime/evening attendance', 'Previous qualification', 'Nacionality',
       'Mother's qualification', 'Father's qualification',
       'Mother's occupation', 'Father's occupation', 'Displaced',
       'Educational special needs', 'Debtor', 'Tuition fees up to date',
       'Gender', 'Scholarship holder', 'Age at enrollment', 'International',
       'Curricular units 1st sem (credited)',
       'Curricular units 1st sem (enrolled)',
       'Curricular units 1st sem (evaluations)',
       'Curricular units 1st sem (approved)',
       'Curricular units 1st sem (grade)',
       'Curricular units 1st sem (without evaluations)',
       'Curricular units 2nd sem (credited)',
       'Curricular units 2nd sem (enrolled)',
       'Curricular units 2nd sem (evaluations)',
       'Curricular units 2nd sem (approved)',
       'Curricular units 2nd sem (grade)',
       'Curricular units 2nd sem (without evaluations)

In [105]:
X = df.drop(columns=['Target']).to_numpy()
y = df['Target']

In [106]:
X = X[:3500]
y = y[:3500]

In [107]:
print(X.shape)
print(y.shape)

(3500, 34)
(3500,)


In [108]:
from sklearn.model_selection import train_test_split

# Splitting a dataset into a training set and a testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [130]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

class NeuralNet:
    def __init__(self):
        rng = np.random.RandomState(42)
        self.W = rng.randn(2800, 34) * 0.1
        self.B1 = np.zeros(2800)
        self.U = rng.randn(2800, 1) * 0.1
        self.B2 = np.zeros(3)

    def forward(self, X):
        self.X = X
        self.A = np.dot(X, self.W.T) + self.B1
        self.H = sigmoid(self.A)
        self.B = np.dot(self.H, self.U) + self.B2
        self.P = sigmoid(self.B)
        return self.P.squeeze()

    def backward(self, dP):
        dB = (1 - self.P) * self.P * dP
        dB2 = np.sum(dB, axis=0)
        dU = np.dot(self.H.T, dB)
        dH = np.dot(dB, self.U.T)
        dA = (1 - self.H) * self.H * dH
        dB1 = np.sum(dA, axis=0)
        dW = np.dot(self.X.T, dA)
        self.dU = dU
        self.dW = dW
        self.dB1 = dB1
        self.dB2 = dB2


def loss(pred, y):
    # neg log likelihood
    return - (y * np.log(pred) + (1 - y) * np.log(1 - pred)).mean()

def dloss(pred, y):
    # grad w.r.t. pred
    return - (y / pred - (1 - y) / (1 - pred)) / pred.size

def dloss_num(pred, y):
    eps = 1e-6
    n = pred.size
    loss0 = loss(pred, y)
    grad_num = np.zeros_like(pred)
    for i in range(n):
        p0 = pred[i]
        pred[i] += eps
        dl = loss(pred, y) - loss0
        grad_num[i] = dl / eps
        pred[i] = p0
    return grad_num

def dW_num(nn, X, y):
    eps = 1e-6
    loss0 = loss(nn.forward(X), y)
    grad_num = np.zeros_like(nn.W)

    for i in range(nn.W.shape[0]):
        for j in range(nn.W.shape[1]):
            w0 = nn.W[i, j]
            nn.W[i, j] += eps
            dl = loss(nn.forward(X), y) - loss0
            grad_num[i, j] = dl / eps
            nn.W[i, j] = w0
    return grad_num

def dU_num(nn, X, y):
    eps = 1e-6
    loss0 = loss(nn.forward(X), y)
    grad_num = np.zeros_like(nn.U)

    for i in range(nn.U.shape[0]):
        for j in range(nn.U.shape[1]):
            u0 = nn.U[i, j]
            nn.U[i, j] += eps
            dl = loss(nn.forward(X), y) - loss0
            grad_num[i, j] = dl / eps
            nn.U[i, j] = u0
    return grad_num

def dB1_num(nn, X, y):
    eps = 1e-6
    loss0 = loss(nn.forward(X), y)
    grad_num = np.zeros_like(nn.B1)

    for i in range(nn.B1.size):
        b0 = nn.B1[i]
        nn.B1[i] += eps
        dl = loss(nn.forward(X), y) - loss0
        grad_num[i] = dl / eps
        nn.B1[i] = b0
    return grad_num

def dB2_num(nn, X, y):
    eps = 1e-6
    loss0 = loss(nn.forward(X), y)
    grad_num = np.zeros_like(nn.B2)

    for i in range(nn.B2.size):
        b0 = nn.B2[i]
        nn.B2[i] += eps
        dl = loss(nn.forward(X), y) - loss0
        grad_num[i] = dl / eps
        nn.B2[i] = b0
    return grad_num

In [131]:
# Test forward computation and derivative of Loss / network output
nn = NeuralNet()
pred = nn.forward(X_train)

ValueError: shapes (2800,34) and (17,2800) not aligned: 34 (dim 1) != 17 (dim 0)

In [128]:
print(pred)

[[0.03709148 0.03709148 0.03709148]
 [0.1263028  0.1263028  0.1263028 ]
 [0.03889804 0.03889804 0.03889804]
 ...
 [0.0406724  0.0406724  0.0406724 ]
 [0.00501149 0.00501149 0.00501149]
 [0.03784249 0.03784249 0.03784249]]


In [129]:
print(pred[:5], y_train[:5])
print(loss(pred, y_train))
print(dloss(pred, y_train))
print(dloss_num(pred, y_train))

[[0.03709148 0.03709148 0.03709148]
 [0.1263028  0.1263028  0.1263028 ]
 [0.03889804 0.03889804 0.03889804]
 [0.03969714 0.03969714 0.03969714]
 [0.00463028 0.00463028 0.00463028]] 162     Graduate
1001     Dropout
1718     Dropout
1003    Graduate
1233    Graduate
Name: Target, dtype: object


ValueError: operands could not be broadcast together with shapes (2800,) (2800,3) 